application: "jaikuengine"
version: 1
runtime: python
api_version: 1
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (manage.py)|
 (simplejson/.*)|
 (gdata/.*)|
 (atom/.*)|
 (tlslite/.*)|
 (oauth/.*)|
 (beautifulsoup/.*)|
 (django/.*)|
 (docutils/.*)|
 (epydoc/.*)|
 (appengine_django/management/commands/.*)|
 (README)|
 (CHANGELOG)|
 (Makefile)|
 (bin/.*)|
 (images/ads/.*)|
 (images/ext/.*)|
 (wsgiref/.*)|
 (elementtree/.*)|
 (doc/.*)|
 (profiling/.*)|
 (vendor/.*)
 )$

default_expiration: "1d"

handlers:
- url: /images
  static_dir: images

- url: /image/(avatar_default.*)
  static_files: image/\1
  upload: image/avatar_default.*

- url: /image/default
  static_dir: image/default

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /static
  static_dir: static

- url: /themes
  static_dir: themes

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /load
  script: "$PYTHON_LIB/google/appengine/ext/remote_api/handler.py"
  login: admin

- url: /api/process_queue
  script: "main.py"
  secure: optional

- url: .*
  script: "main.py"
  secure: optional
  # login: admin
